/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas.pantallasClientes;

import Renders.RenderLiquidacion;
import Usuarios.InicioSesion;
import pantallas.*;
import entidades.Cliente;
import entidades.Contrato;
import entidades.Cuotas;
import entidades.Eventos;
import entidades.Inmueble;
import gestores.GestorAltaInmueble;
import gestores.GestorEventos;
import gestores.GestorModificarInmueble;
import gestores.GestoresContrato;
import gestores.gestoresCliente.BusquedaCliente;
import gestores.gestoresCliente.GestorEliminarCliente;
import gestores.gestoresCliente.GestorModificarCliente;
import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import modelos.ModeloDetalleCuotasContrato;
import modelos.ModeloTablaContratosDelCliente;
import static pantallas.PrincipalAdministrador.diaPago;
import static pantallas.PrincipalAdministrador.idConsAsociado;
import static pantallas.PrincipalAdministrador.idInmDatos;
import static pantallas.PrincipalAdministrador.inicioCon;
import static pantallas.PrincipalAdministrador.tablaContratos;

/**
 *
 * @author Nahuel
 */
public class DatosCliente extends javax.swing.JFrame {

    /**
     * Creates new form AltaInmueble
     */
    public DatosCliente() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        fechaNac = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        dni = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        profesion = new javax.swing.JTextField();
        ciudad = new javax.swing.JTextField();
        celular = new javax.swing.JTextField();
        dgi = new javax.swing.JTextField();
        apellidoM = new javax.swing.JTextField();
        provincia = new javax.swing.JTextField();
        estadoCivil = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        cuit = new javax.swing.JTextField();
        idPropietario = new javax.swing.JLabel();
        btnEliminarCliente = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaContratosCliente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Datos del Cliente");
        setLocation(new java.awt.Point(650, 150));

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Cliente"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Id Cliente: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombre: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Apellido:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Apellido Materno:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("DNI: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Fecha Nacimiento: ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Estado Civil:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Profesion: ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Direccion:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Ciudad: ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Provincia:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Telefono: ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Celular:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("E-Mail:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("DGI: ");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("CUIT: ");

        nombre.setEditable(false);
        nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        apellido.setEditable(false);
        apellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoActionPerformed(evt);
            }
        });

        fechaNac.setEditable(false);
        fechaNac.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        direccion.setEditable(false);
        direccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionActionPerformed(evt);
            }
        });

        dni.setEditable(false);
        dni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        telefono.setEditable(false);
        telefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        profesion.setEditable(false);
        profesion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ciudad.setEditable(false);
        ciudad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        celular.setEditable(false);
        celular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        dgi.setEditable(false);
        dgi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        apellidoM.setEditable(false);
        apellidoM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        provincia.setEditable(false);
        provincia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        estadoCivil.setEditable(false);
        estadoCivil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        correo.setEditable(false);
        correo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cuit.setEditable(false);
        cuit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        idPropietario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idPropietario)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombre)
                                    .addComponent(direccion)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(profesion)
                                    .addComponent(telefono)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ciudad)
                                            .addComponent(dni, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel15))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(celular)
                                            .addComponent(dgi))))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(19, 19, 19)
                                        .addComponent(cuit))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel14))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(apellidoM)
                                            .addComponent(estadoCivil)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(provincia, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(correo))))))
                        .addGap(81, 81, 81))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idPropietario))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(provincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(fechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(estadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(profesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dgi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnEliminarCliente.setText("Eliminar");
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Editar");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contratos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jScrollPane1.setBorder(null);

        tablaContratosCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Inmueble", "Rol en Contrato"
            }
        ));
        tablaContratosCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaContratosClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaContratosCliente);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEliminarCliente)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 502, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(293, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(btnEliminarCliente)
                    .addComponent(jCheckBox1))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 288, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if(jCheckBox1.isSelected()){                  
        Cliente prop=new Cliente();     
        prop.setApellido(apellido.getText());
        prop.setApellidoMaterno(apellidoM.getText());
        prop.setCelular(Integer.parseInt(celular.getText()));
        prop.setCorreo(correo.getText());
        prop.setCuit(Integer.parseInt(cuit.getText()));
        prop.setDgi(dgi.getText());
        prop.setDireccion(direccion.getText());
        prop.setDni(Integer.parseInt(dni.getText()));
        prop.setEstadoCivil(estadoCivil.getText());
        prop.setFechaNac(fechaNac.getText());
        prop.setId(Integer.parseInt(idPropietario.getText()));
        prop.setLocalidad(ciudad.getText());
        prop.setNombre(nombre.getText());
        prop.setProfesion(profesion.getText());
        prop.setProvincia(provincia.getText());
        prop.setTel(Integer.parseInt(telefono.getText()));
        
        GestorModificarCliente gest=new GestorModificarCliente();
        try {
            gest.modificarCliente(prop);
        } catch (IOException ex) {
            Logger.getLogger(DatosCliente.class.getName()).log(Level.SEVERE, null, ex);
        }								
        JOptionPane.showMessageDialog(new JDialog(),"Guardado Correctamente");  
        Eventos evento=new Eventos();            
        evento.setUsuario(InicioSesion.usuarioEnSesion);
        evento.setTipo("CLIENTE");
        evento.setDescipcion("Se modifico el Cliente "+prop.getNombre()+" "+prop.getApellido()+" "+prop.getApellidoMaterno());
        evento.setFecha(GestorEventos.getFechaActual());
            try {
                int e=GestorEventos.AltaEvento(evento);
            } catch (IOException ex) {
                Logger.getLogger(DatosCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        dispose();				        
        }else{
            dispose();
        }

        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed

        Cliente cliente=new Cliente();
        cliente.setId(Integer.parseInt(idPropietario.getText()));
        cliente.setApellido(apellido.getText());
        cliente.setNombre(nombre.getText());
        cliente.setApellidoMaterno(apellidoM.getText());
        String b=GestoresContrato.ConsultarClienteEnContrato(cliente.getId());
        if(b.equals("Si")){
            JOptionPane.showMessageDialog(new JDialog(),"No se puede eliminar el cliente porque pertenece a un contrato"); 
        }else{
            GestorEliminarCliente gestElim=new GestorEliminarCliente();
            Eventos evento=new Eventos();            
        evento.setUsuario(InicioSesion.usuarioEnSesion);
        evento.setTipo("CLIENTE");
        evento.setDescipcion("Se elimino el Cliente "+cliente.getNombre()+" "+cliente.getApellido()+" "+cliente.getApellidoMaterno());
        evento.setFecha(GestorEventos.getFechaActual());
        int r;
        try {
            r = gestElim.gestorEliminarCliente(cliente.getId());
            if(r==0){                           
            }else{
                JOptionPane.showMessageDialog(new JDialog(),"Eliminado Correctamente");   
                int e=GestorEventos.AltaEvento(evento);
            }
        } catch (IOException ex) {
            Logger.getLogger(DatosCliente.class.getName()).log(Level.SEVERE, null, ex);
        }      		
        dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed

        if(jCheckBox1.isSelected()){
            apellido.setEditable(true);
            direccion.setEditable(true);
            fechaNac.setEditable(true);
            estadoCivil.setEditable(true);
            nombre.setEditable(true);
            apellidoM.setEditable(true);
            dni.setEditable(true);
            ciudad.setEditable(true);
            correo.setEditable(true);
            celular.setEditable(true);
            cuit.setEditable(true);
            dgi.setEditable(true);
            provincia.setEditable(true);
            profesion.setEditable(true);
            telefono.setEditable(true);
            jButton2.setText("Guardar");
        }else{
            apellido.setEditable(false);
            direccion.setEditable(false);
            fechaNac.setEditable(false);
            estadoCivil.setEditable(false);
            nombre.setEditable(false);
            apellidoM.setEditable(false);
            dni.setEditable(false);
            ciudad.setEditable(false);
            correo.setEditable(false);
            celular.setEditable(false);
            cuit.setEditable(false);
            dgi.setEditable(false);
            provincia.setEditable(false);
            profesion.setEditable(false);
            telefono.setEditable(false);
            jButton2.setText("Aceptar");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void tablaContratosClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaContratosClienteMouseClicked

         if(evt.getClickCount()==2){
        int row = tablaContratosCliente.getSelectedRow();
        
	    int id=Integer.parseInt(tablaContratosCliente.getValueAt(row, 0).toString());
            idInmDatos=GestoresContrato.idInm(id);
            Inmueble inmDetalle=GestoresContrato.consultaInmuebleDetalle(idInmDatos);
            String inmuebleTitulo=inmDetalle.getCalle()+" "+inmDetalle.getPiso()+" "+inmDetalle.getDpto();
            inicioCon=(String) tablaContratosCliente.getValueAt(row, 2);
            idConsAsociado=Integer.parseInt(tablaContratosCliente.getValueAt(row, 0).toString());
            DetallesContrato detalles=new DetallesContrato();
            detalles.pack();
            detalles.setLocationRelativeTo(null);
            detalles.setExtendedState(MAXIMIZED_BOTH);
            ArrayList<Cuotas> contCuo2=GestoresContrato.consultarCuotas(id);
            ModeloDetalleCuotasContrato mdcc=new ModeloDetalleCuotasContrato(contCuo2);
            DetallesContrato.tablaDetalle.setModel(mdcc);
            DetallesContrato.lblIdContrato.setText(Integer.toString(id));
            DetallesContrato.lblInmueble.setText(inmuebleTitulo);
            DetallesContrato.tablaDetalle.setDefaultRenderer(Object.class, new RenderLiquidacion());   
            DetallesContrato.tablaDetalle.setRowHeight(25);
            DetallesContrato.tablaDetalle.getTableHeader().setPreferredSize(
            new Dimension(DetallesContrato.tablaDetalle.getColumnModel().getTotalColumnWidth(),40));
            ((DefaultTableCellRenderer)DetallesContrato.tablaDetalle.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
            
            DetallesContrato.tablaImpuestos.getTableHeader().setPreferredSize(
            new Dimension(DetallesContrato.tablaImpuestos.getColumnModel().getTotalColumnWidth(),40));
            ((DefaultTableCellRenderer)DetallesContrato.tablaImpuestos.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
            
            diaPago=GestoresContrato.consultaDatosContrato(id).getDiaPago();

            if(InicioSesion.usuarioEnSesion.getTipo().equals("EMPLEADO")){
               DetallesContrato.btnRescindir.setEnabled(false); 
            }

                DetallesContrato.habilitarTabla=true;
                      
            detalles.setVisible(true);
            
}
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaContratosClienteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new DatosCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField apellido;
    public javax.swing.JTextField apellidoM;
    public static javax.swing.JButton btnEliminarCliente;
    public javax.swing.JTextField celular;
    public javax.swing.JTextField ciudad;
    public javax.swing.JTextField correo;
    public javax.swing.JTextField cuit;
    public javax.swing.JTextField dgi;
    public javax.swing.JTextField direccion;
    public javax.swing.JTextField dni;
    public javax.swing.JTextField estadoCivil;
    public javax.swing.JTextField fechaNac;
    public javax.swing.JLabel idPropietario;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField nombre;
    public javax.swing.JTextField profesion;
    public javax.swing.JTextField provincia;
    public static javax.swing.JTable tablaContratosCliente;
    public javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables

 
    
}
