
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas.pantallasClientes;

import Renders.RenderLiquidacion;
import Usuarios.InicioSesion;
import pantallas.*;
import entidades.Cliente;
import entidades.Cuotas;
import entidades.Inmueble;
import gestores.GestoresContrato;
import gestores.gestoresCliente.BusquedaPropietario;
import java.awt.Dimension;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import modelos.ModeloDetalleCuotasContrato;
import modelos.ModeloTablaPropietarioResumen;
import static pantallas.PrincipalAdministrador.diaPago;
import static pantallas.PrincipalAdministrador.idConsAsociado;
import static pantallas.PrincipalAdministrador.idInmDatos;
import static pantallas.PrincipalAdministrador.inicioCon;
import static pantallas.PrincipalAdministrador.tablaContratos;

import pantallas.pantallasClientes.DatosCliente;

/**
 *
 * @author Nahuel
 */
public class ListaBusquedaContrato extends javax.swing.JFrame {

    /**
     * Creates new form ListaPropietarios
     */
    public ListaBusquedaContrato() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListaBusquedaContrato = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista Contratos");

        tablaListaBusquedaContrato.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablaListaBusquedaContratoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tablaListaBusquedaContrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaListaBusquedaContratoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaListaBusquedaContrato);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1198, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaListaBusquedaContratoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablaListaBusquedaContratoAncestorAdded
        // TODO add your handling code here:
        
                                
    }//GEN-LAST:event_tablaListaBusquedaContratoAncestorAdded

    private void tablaListaBusquedaContratoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaListaBusquedaContratoMouseClicked
      if(evt.getClickCount()==2){

            int row = tablaListaBusquedaContrato.getSelectedRow();
	    int id=Integer.parseInt(tablaListaBusquedaContrato.getValueAt(row, 0).toString());           
            idInmDatos=GestoresContrato.idInm(id);                      
            Inmueble inmDetalle=GestoresContrato.consultaInmuebleDetalle(idInmDatos);
            String inmuebleTitulo=inmDetalle.getCalle()+" "+inmDetalle.getPiso()+" "+inmDetalle.getDpto();                    
            inicioCon=(String) tablaListaBusquedaContrato.getValueAt(row, 7);
            idConsAsociado=Integer.parseInt(tablaListaBusquedaContrato.getValueAt(row, 0).toString());                       
            DetallesContrato detalles=new DetallesContrato();
            detalles.pack();
            detalles.setLocationRelativeTo(null);
            detalles.setExtendedState(MAXIMIZED_BOTH);
            ArrayList<Cuotas> contCuo2=GestoresContrato.consultarCuotas(id);
            ModeloDetalleCuotasContrato mdcc=new ModeloDetalleCuotasContrato(contCuo2);
            DetallesContrato.tablaDetalle.setModel(mdcc);
            DetallesContrato.lblIdContrato.setText(Integer.toString(id));
            DetallesContrato.lblInmueble.setText(inmuebleTitulo);
            DetallesContrato.tablaDetalle.setDefaultRenderer(Object.class, new RenderLiquidacion());   
            DetallesContrato.tablaDetalle.setRowHeight(25);
            DetallesContrato.tablaDetalle.getTableHeader().setPreferredSize(
            new Dimension(DetallesContrato.tablaDetalle.getColumnModel().getTotalColumnWidth(),40));
            ((DefaultTableCellRenderer)DetallesContrato.tablaDetalle.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);            
            diaPago=GestoresContrato.consultaDatosContrato(id).getDiaPago();
            if(InicioSesion.usuarioEnSesion.getTipo().equals("EMPLEADO")){
               DetallesContrato.btnRescindir.setEnabled(false); 
            }
            detalles.setVisible(true);
            dispose();
       }
       
    }//GEN-LAST:event_tablaListaBusquedaContratoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaBusquedaContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaBusquedaContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaBusquedaContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaBusquedaContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaBusquedaContrato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tablaListaBusquedaContrato;
    // End of variables declaration//GEN-END:variables

}
