/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

import Usuarios.InicioSesion;
import entidades.Cliente;
import entidades.Eventos;
import gestores.BusquedaInmueble;
import gestores.GestorEventos;
import gestores.GestorModificarInmueble;
import gestores.gestoresCliente.BusquedaPropietario;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;
import modelos.ModeloTablaInmueble;
import modelos.ModeloTablaInmuebleContrato;

import pantallas.pantallasClientes.DatosCliente;
import static pantallas.ListaRecuperarInmueble.tablaRecuperarInmuebles;

/**
 *
 * @author Nahuel
 */
public class ListaRecuperarInmueble extends javax.swing.JFrame {

    /**
     * Creates new form ListaPropietarios
     */
    public ListaRecuperarInmueble() {
        initComponents();
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRecuperarInmuebles = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextBusquedaInm = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de Inmuebles");
        setLocation(new java.awt.Point(650, 150));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jScrollPane1.setBorder(null);

        tablaRecuperarInmuebles.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablaRecuperarInmueblesAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tablaRecuperarInmuebles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaRecuperarInmueblesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaRecuperarInmuebles);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(java.awt.Color.red);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextBusquedaInm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextBusquedaInm.setToolTipText("Calle y Numero o Propietario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jTextBusquedaInm, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(822, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextBusquedaInm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaRecuperarInmueblesAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablaRecuperarInmueblesAncestorAdded
        // TODO add your handling code here:
        
                                
    }//GEN-LAST:event_tablaRecuperarInmueblesAncestorAdded

    private void tablaRecuperarInmueblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaRecuperarInmueblesMouseClicked
        if(evt.getClickCount()==2){
            String direccion=tablaRecuperarInmuebles.getValueAt(tablaRecuperarInmuebles.getSelectedRow(), 1).toString();
            int idInmueble=Integer.parseInt(tablaRecuperarInmuebles.getValueAt(tablaRecuperarInmuebles.getSelectedRow(), 0).toString());
            Object[] opciones = {"Aceptar", "Cancelar"};
            int eleccion = JOptionPane.showOptionDialog(null, "¿Desea recuperar el Inmueble "+direccion+" ?", "Mensaje de Confirmacion",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE, null, opciones, "Cancelar");
            if (eleccion == JOptionPane.YES_OPTION) {       
                int r=GestorModificarInmueble.ModificarEstadoDisponible(idInmueble);
                Eventos evento=new Eventos();            
           
                evento.setUsuario(InicioSesion.usuarioEnSesion);            
                evento.setTipo("INMUEBLE");          
                evento.setDescipcion("Se recupero el Inmueble "+direccion);         
                evento.setFecha(GestorEventos.getFechaActual());
                if(r==1){
                    JOptionPane.showMessageDialog(new JDialog(),"El Inmueble se recupero con exito");
                    try {
                        int e=GestorEventos.AltaEvento(evento);
                    } catch (IOException ex) {
                        Logger.getLogger(ListaRecuperarInmueble.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
       
    }//GEN-LAST:event_tablaRecuperarInmueblesMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       ArrayList listaRecuperarInmueble=BusquedaInmueble.consultaTablaRecuperarInmueble(jTextBusquedaInm.getText());
       ModeloTablaInmuebleContrato modelo=new ModeloTablaInmuebleContrato(listaRecuperarInmueble);
       tablaRecuperarInmuebles.setModel(modelo);
       tablaRecuperarInmuebles.getColumnModel().getColumn(0).setMaxWidth(50);
       tablaRecuperarInmuebles.getColumnModel().getColumn(2).setMaxWidth(50);
       tablaRecuperarInmuebles.getColumnModel().getColumn(3).setMaxWidth(50);
      


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

        ArrayList listaInmueble=BusquedaInmueble.consultaTablaInmuebleRecuperar();
        ModeloTablaInmuebleContrato modelo=new ModeloTablaInmuebleContrato(listaInmueble);
        tablaRecuperarInmuebles.setModel(modelo);
        tablaRecuperarInmuebles.getColumnModel().getColumn(0).setMaxWidth(50);
        tablaRecuperarInmuebles.getColumnModel().getColumn(2).setMaxWidth(50);
        tablaRecuperarInmuebles.getColumnModel().getColumn(3).setMaxWidth(50);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaRecuperarInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaRecuperarInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaRecuperarInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaRecuperarInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaRecuperarInmueble().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextBusquedaInm;
    public static javax.swing.JTable tablaRecuperarInmuebles;
    // End of variables declaration//GEN-END:variables

    
    


}
