/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

import Usuarios.InicioSesion;
import entidades.Cliente;
import entidades.Inmueble;
import gestores.BusquedaInmueble;
import gestores.gestoresCliente.BusquedaPropietario;
import java.util.ArrayList;
import javax.swing.table.TableColumnModel;
import modelos.ModeloTablaInmueble;
import modelos.ModeloTablaInmuebleContrato;

import pantallas.pantallasClientes.DatosCliente;

/**
 *
 * @author Nahuel
 */
public class ListaBusquedaInmueble extends javax.swing.JFrame {

    /**
     * Creates new form ListaPropietarios
     */
    public ListaBusquedaInmueble() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListaInmuebles2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de Inmuebles");
        setLocation(new java.awt.Point(650, 150));

        jScrollPane1.setBorder(null);

        tablaListaInmuebles2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablaListaInmuebles2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tablaListaInmuebles2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaListaInmuebles2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaListaInmuebles2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaListaInmuebles2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablaListaInmuebles2AncestorAdded
        // TODO add your handling code here:
        
                                
    }//GEN-LAST:event_tablaListaInmuebles2AncestorAdded

    private void tablaListaInmuebles2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaListaInmuebles2MouseClicked
        if(evt.getClickCount()==2){
          
						int row = tablaListaInmuebles2.getSelectedRow();
                                
				String id=tablaListaInmuebles2.getValueAt(row, 0).toString();
				Inmueble datos=BusquedaInmueble.busquedaDatosInmueble(Integer.parseInt(id));
				DatosInmueble pantaDatos=new DatosInmueble();
                                
                                pantaDatos.propietario.setText(datos.getPropietario().getId()+" - "+datos.getPropietario().getApellido()+" "+datos.getPropietario().getNombre());
                                pantaDatos.calle.setText(datos.getCalle());
                                pantaDatos.ciudad.setText(datos.getLocalidad());
                                pantaDatos.dpto.setText(datos.getDpto());
                                pantaDatos.estado.setText(datos.getEstado());
                                pantaDatos.fechaInscripcion.setText(datos.getFechaInscripcion());
                                pantaDatos.folio.setText((datos.getFolio()));
                                pantaDatos.nroFolio.setText(Integer.toString(datos.getFolioReal()));
                                pantaDatos.piso.setText(datos.getPiso());
                                pantaDatos.tipo.setText(datos.getTipo());
                                pantaDatos.tomo.setText(Integer.toString(datos.getTomo()));
                                pantaDatos.etiquetaId.setText(Integer.toString(datos.getId()));
                                pantaDatos.ciudad.setText(datos.getLocalidad());
                                pantaDatos.provincia.setText(datos.getProvincia());
                                 
                                if(InicioSesion.usuarioEnSesion.getTipo().equals("EMPLEADO")){
                                    pantaDatos.btnEliminarInmueble.setEnabled(false);
                                }
                                pantaDatos.setVisible(true);
				
                                
				dispose();
       }
       
    }//GEN-LAST:event_tablaListaInmuebles2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaBusquedaInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaBusquedaInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaBusquedaInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaBusquedaInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaBusquedaInmueble().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tablaListaInmuebles2;
    // End of variables declaration//GEN-END:variables


}
