/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;


import Usuarios.InicioSesion;
import static com.sun.org.apache.xerces.internal.util.FeatureState.is;
import entidades.Cliente;
import entidades.Contrato;
import entidades.Cuotas;
import entidades.DescripcionImpuesto;
import entidades.Eventos;
import entidades.Inmueble;
import entidades.Movimiento;
import entidades.TitularImpuesto;
import gestores.BusquedaInmueble;
import Excepciones.ExcepcionClientesContrato;
import Excepciones.ExcepcionGarantia;
import Excepciones.ExcepcionIntervalo;
import entidades.Parametros;
import gestores.GestorEventos;
import gestores.GestorModificarInmueble;
import gestores.GestorParametros;
import gestores.GestoresContrato;
import gestores.GestoresImpuestos;
import gestores.fechas;
import gestores.gestoresCliente.BusquedaPropietario;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;

import static pantallas.NuevoContrato.tablaCuota;
import static pantallas.NuevoPrecio.desdeCuota;
import static pantallas.NuevoPrecio.hastaCuota;

import pantallas.pantallasClientes.ListaGarantesNuevoContrato1;
import pantallas.pantallasClientes.ListaGarantesNuevoContrato2;
import pantallas.pantallasClientes.ListaInquilinoNuevoContrato;


/**
 *
 * @author Nahuel
 */
public class NuevoContrato extends javax.swing.JFrame {

    static JDialog contratoDoc= new JDialog(new JFrame(),"Contrato",true);
    Dimension dimension=Toolkit.getDefaultToolkit().getScreenSize();
    int alto=(int) dimension.getWidth();
    int ancho=(int) dimension.getHeight();
    /**
     * Creates new form NuevoContrato
     */
    public NuevoContrato() throws SQLException {
        initComponents();
        this.setResizable(false);
        TableColumn columna=null;
        columna=tablaCuota.getColumnModel().getColumn(4);
        columna.setPreferredWidth(1);
        
        ArrayList<Parametros> parametro=GestorParametros.consultaParametros();
        double p=parametro.get(0).getPorcentajePunitorios();
        double c=parametro.get(0).getProcentajeComision();
        
        comision.setText(Double.toString(c));
        punitorios.setText(Double.toString(p));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inmueble = new javax.swing.JTextField();
        propietario = new javax.swing.JTextField();
        inquilino = new javax.swing.JTextField();
        garante1 = new javax.swing.JTextField();
        garante2 = new javax.swing.JTextField();
        seleccionarInquilino = new javax.swing.JButton();
        seleccionarInmueble = new javax.swing.JButton();
        seleccionarGara1 = new javax.swing.JButton();
        seleccionarGara2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        numeroContrato = new javax.swing.JTextField();
        diaPago = new javax.swing.JTextField();
        fechaComienzo = new com.toedter.calendar.JDateChooser();
        fechaVencimiento = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCuota = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        garantia = new javax.swing.JTextField();
        comision = new javax.swing.JTextField();
        punitorios = new javax.swing.JTextField();
        comboComision = new javax.swing.JComboBox<>();
        comboPunitorio = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cuotasGarantia = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        imp1 = new javax.swing.JTextField();
        imp2 = new javax.swing.JTextField();
        imp3 = new javax.swing.JTextField();
        imp4 = new javax.swing.JTextField();
        imp5 = new javax.swing.JTextField();
        imp6 = new javax.swing.JTextField();
        imp7 = new javax.swing.JTextField();
        imp8 = new javax.swing.JTextField();
        imp9 = new javax.swing.JTextField();
        imp10 = new javax.swing.JTextField();
        imp11 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        imp12 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(650, 150));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Inmueble:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Propietario:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Inquilino:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Garante 1:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Garante 2:");

        inmueble.setEditable(false);

        propietario.setEditable(false);
        propietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propietarioActionPerformed(evt);
            }
        });

        inquilino.setEditable(false);

        garante1.setEditable(false);

        garante2.setEditable(false);
        garante2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                garante2ActionPerformed(evt);
            }
        });

        seleccionarInquilino.setText("...");
        seleccionarInquilino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarInquilinoActionPerformed(evt);
            }
        });

        seleccionarInmueble.setText("...");
        seleccionarInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarInmuebleActionPerformed(evt);
            }
        });

        seleccionarGara1.setText("...");
        seleccionarGara1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarGara1ActionPerformed(evt);
            }
        });

        seleccionarGara2.setText("...");
        seleccionarGara2.setEnabled(false);
        seleccionarGara2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarGara2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(inmueble, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(propietario)
                            .addComponent(inquilino))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(seleccionarInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(garante2))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(garante1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seleccionarGara1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seleccionarGara2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(seleccionarInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(inmueble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(garante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seleccionarInmueble)
                    .addComponent(seleccionarGara1))
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(propietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(garante2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seleccionarGara2))
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seleccionarInquilino))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Contrato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Numero de Contrato: ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Fecha Comienzo: ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Fecha de Vencimiento: ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Dia de Pago:  ");

        numeroContrato.setEditable(false);
        numeroContrato.setText(Integer.toString(pantallas.PrincipalAdministrador.x)
        );
        numeroContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroContratoActionPerformed(evt);
            }
        });

        diaPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                diaPagoKeyTyped(evt);
            }
        });

        fechaComienzo.setDateFormatString("dd/MM/yyyy");

        fechaVencimiento.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaVencimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numeroContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaComienzo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(269, 269, 269))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(numeroContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaComienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(fechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(diaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jButton1.setText("Cargar Contrato");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Datos Principales", jPanel1);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Montos por periodo: ");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("+Nuevo Precio/Periodo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tablaCuota = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        tablaCuota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cuota Inicial", "Cuota Final", "Monto Alquiler", "Monto Total","  "
            }
        ));
        tablaCuota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCuotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCuota);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Comision:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Deposito Garantia:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Punitorios:");

        garantia.setText("0");
        garantia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                garantiaActionPerformed(evt);
            }
        });
        garantia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                garantiaKeyTyped(evt);
            }
        });

        comision.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                comisionKeyTyped(evt);
            }
        });

        punitorios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                punitoriosKeyTyped(evt);
            }
        });

        comboComision.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "% Procentual","Monto Fijo" }));

        comboPunitorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "% Porcentual","Monto Fijo" }));

        jLabel14.setText("(por dia)");

        jLabel16.setText("Cuotas Garantia: ");

        cuotasGarantia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cuotasGarantia.setText("1");
        cuotasGarantia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cuotasGarantiaKeyTyped(evt);
            }
        });

        jLabel29.setText("Todos los valores se representan el ($) Peso Argentino");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13))
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(garantia)
                            .addComponent(comision)
                            .addComponent(punitorios, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboComision, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboPunitorio, 0, 171, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cuotasGarantia)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(garantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(cuotasGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(comision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(punitorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboPunitorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Montos del Contrato", jPanel2);

        imp1.setText(" ");
        imp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imp1ActionPerformed(evt);
            }
        });

        imp2.setText(" ");

        imp3.setText(" ");
        imp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imp3ActionPerformed(evt);
            }
        });

        imp4.setText(" ");

        imp5.setText(" ");

        imp6.setText(" ");

        imp7.setText(" ");

        imp8.setText(" ");

        imp9.setText(" ");

        imp10.setText(" ");

        imp11.setText(" ");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Numeros de asociado:");

        imp12.setText(" ");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Inmobiliario");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Tasa Municipal");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Luz");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Agua Potable");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Gas");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Cable Video");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Internet");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Telefono");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Celular");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Cloaca");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Sepelio");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Cuenca");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addGap(246, 246, 246)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(imp1)
                    .addComponent(imp2)
                    .addComponent(imp3)
                    .addComponent(imp4)
                    .addComponent(imp5)
                    .addComponent(imp6)
                    .addComponent(imp7)
                    .addComponent(imp8)
                    .addComponent(imp9)
                    .addComponent(imp10)
                    .addComponent(imp11, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(imp12))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel15)
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(imp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(imp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addComponent(imp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imp7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imp8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imp9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imp10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imp11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imp12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Impuestos/Servicios", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void propietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_propietarioActionPerformed

    private void garante2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_garante2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_garante2ActionPerformed

    private void seleccionarInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarInmuebleActionPerformed
    ListaInmueble  pantalistainmueble= new ListaInmueble();
    pantalistainmueble.pack();
    pantalistainmueble.setLocationRelativeTo(null);
    pantalistainmueble.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionarInmuebleActionPerformed

    private void seleccionarInquilinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarInquilinoActionPerformed

        ListaInquilinoNuevoContrato listainq=new ListaInquilinoNuevoContrato();
        listainq.pack();
        listainq.setLocationRelativeTo(null);
        listainq.setVisible(true);
   
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionarInquilinoActionPerformed

    private void seleccionarGara1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarGara1ActionPerformed
    ListaGarantesNuevoContrato1 listaG2=new ListaGarantesNuevoContrato1();       
    listaG2.pack();
    listaG2.setLocationRelativeTo(null);
    listaG2.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionarGara1ActionPerformed

    private void seleccionarGara2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarGara2ActionPerformed

    ListaGarantesNuevoContrato2 listaG3=new ListaGarantesNuevoContrato2();
    listaG3.pack();
    listaG3.setLocationRelativeTo(null);
    listaG3.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionarGara2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
DefaultTableModel model=(DefaultTableModel)tablaCuota.getModel();

        NuevoPrecio precio=new NuevoPrecio();
        precio.pack();
        precio.setLocationRelativeTo(null);

            int filas=(model.getRowCount())-1;
                 if(tablaCuota.getRowCount()!=0 ){  
                   ultimaC=(Integer.parseInt((String) tablaCuota.getValueAt(filas, 1)))+1;
                   desdeCuota.setText(Integer.toString(ultimaC));
                  }else{
                         int ultima2=1;
                          desdeCuota.setText(Integer.toString(ultima2));
                  }
         try{
               
        String diaC=Integer.toString( fechaComienzo.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mesCc=Integer.toString(fechaComienzo.getCalendar().get(Calendar.MONTH));
        String añoCc=Integer.toString(fechaComienzo.getCalendar().get(Calendar.YEAR));
        String fechaCcomienzo=diaC+"/"+mesCc+"/"+añoCc;
        
        String diaVv=Integer.toString( fechaVencimiento.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mesVv=Integer.toString(fechaVencimiento.getCalendar().get(Calendar.MONTH));
        String añoVv=Integer.toString(fechaVencimiento.getCalendar().get(Calendar.YEAR));
        String fechavVencimiento=diaVv+"/"+mesVv+"/"+añoVv;
        
        //Calculamos cantidad de cuotas
        SimpleDateFormat formatoDelTexto = new SimpleDateFormat("dd/MM/yyyy");
       
        
        try {

          fechaCc = formatoDelTexto.parse(fechaCcomienzo);
          fechaVv= formatoDelTexto.parse(fechavVencimiento);
          } catch (ParseException ex) {

         ex.printStackTrace();}
        
        cantidadCuotas=fechas.calcularMesesAFecha(fechaCc, fechaVv);
          precio.setVisible(true);     
         }catch(NullPointerException nx){
             JOptionPane.showMessageDialog(new JDialog(),"Ingrese Fecha de Comienzo y Vencimiento del Contrato");
         }                 
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        

        
            
        Contrato contrato=new Contrato();
        Cuotas Cuota=new Cuotas();
        //Pasamos las dechas de comienzo y vencimiento de contrato a String
        try{
            
        
        String diaC=Integer.toString( fechaComienzo.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mesC=Integer.toString(fechaComienzo.getCalendar().get(Calendar.MONTH)+1);
        String añoC=Integer.toString(fechaComienzo.getCalendar().get(Calendar.YEAR));
        String fechaComienzo=diaC+"/"+mesC+"/"+añoC;
        
        String diaV=Integer.toString( fechaVencimiento.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mesV=Integer.toString(fechaVencimiento.getCalendar().get(Calendar.MONTH)+1);
        String añoV=Integer.toString(fechaVencimiento.getCalendar().get(Calendar.YEAR));
        String fechaVencimiento=diaV+"/"+mesV+"/"+añoV;
        
        //Calculamos cantidad de cuotas
        SimpleDateFormat formatoDelTexto = new SimpleDateFormat("dd/MM/yyyy");
        Date fechaC=null;
        Date fechaV=null;
        
        fechaC = formatoDelTexto.parse(fechaComienzo);
          fechaV = formatoDelTexto.parse(fechaVencimiento);
            contrato.setFechaInicio(fechaComienzo);
        contrato.setFechaVencimiento(fechaVencimiento);
        contrato.setTotalCuotas(fechas.calcularMesesAFecha(fechaC, fechaV));
          cantidadCuotas=fechas.calcularMesesAFecha(fechaC, fechaV);
          
        }catch(NullPointerException xx ){
            JOptionPane.showMessageDialog(new JDialog(),"Debe colocar fecha de inicio y vencimiento");
        
          } catch (ParseException ex) {

         ex.printStackTrace();}
        
        
        
        //Sacamos los id de los TextField
        
        String idInm=inmueble.getText();
        String idProp=propietario.getText();
        String idInq=inquilino.getText();
        String idGara1=garante1.getText();
        String idGara2=garante2.getText();
        

        //Cargamos el objeto Contrato
        Inmueble inm=new Inmueble();
        
        Cliente prop=new Cliente();
        Cliente inq=new Cliente();
        Cliente gara1=new Cliente();
        Cliente gara2=new Cliente();
        
        try {
            ExcepcionClientesContrato.validarDatos(idInm, idInq, idGara1, idGara2);
            inm.setId(Integer.parseInt(idInm.substring(0,(idInm.indexOf("-")-1))));
            prop.setId(Integer.parseInt(idProp.substring(0,(idProp.indexOf("-")-1))));
            inm.setPropietario(prop);
        
            inq.setId(Integer.parseInt(idInq.substring(0,(idInq.indexOf("-")-1))));
            gara1.setId(Integer.parseInt(idGara1.substring(0,(idGara1.indexOf("-")-1))));
            gara2.setId(Integer.parseInt(idGara2.substring(0,(idGara2.indexOf("-")-1))));
        } catch (ExcepcionClientesContrato ex) {
            JOptionPane.showMessageDialog(new JDialog(),ex.getMessage());
        }
        
        
        
        contrato.setInmueble(inm);
        contrato.setInquilino(inq);
        contrato.setGarante1(gara1);
        contrato.setGarante2(gara2);

        contrato.setIdContrato(Integer.parseInt(numeroContrato.getText()));
      
        contrato.setCuotaActual(1);
        contrato.setGarantia(Integer.parseInt(garantia.getText()));
        contrato.setEstado("Activo");
        try{
           contrato.setDiaPago(Integer.parseInt(diaPago.getText())); 
        }catch(NumberFormatException ee){
            JOptionPane.showMessageDialog(new JDialog(),"Ingrese el dia de Pago");
        }
        
        contrato.setCuotasGarantia(Integer.parseInt(cuotasGarantia.getText()));
        
        if(comboComision.getSelectedItem().equals("Monto Fijo")){
        
            contrato.setHonorarios(Double.parseDouble(comision.getText()));
            
            
        }else{
           
               contrato.setHonorarios(Double.parseDouble(comision.getText())/100);
            
        }
           if(comboPunitorio.getSelectedItem().equals("Monto Fijo")){
        
         
            contrato.setPunitorios(Double.parseDouble(punitorios.getText()));
            
        }else{
           
             contrato.setPunitorios(Double.parseDouble(punitorios.getText())/100);
            
        }

        


       
        try {
            ExcepcionGarantia.rango(cantidadCuotas, Integer.parseInt(cuotasGarantia.getText()),Integer.parseInt(garantia.getText()));
        } catch (ExcepcionGarantia ex) {
            Logger.getLogger(NuevoContrato.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(contrato.getInmueble().getPropietario().getId()==contrato.getInquilino().getId() || contrato.getInmueble().getPropietario().getId()==contrato.getGarante1().getId() || contrato.getInmueble().getPropietario().getId()==contrato.getGarante2().getId()
                || contrato.getInquilino().getId()==contrato.getGarante1().getId() || contrato.getInquilino().getId()==contrato.getGarante2().getId() || contrato.getGarante1().getId()==contrato.getGarante2().getId()){
            JOptionPane.showMessageDialog(new JDialog(),"Los clientes no se pueden repetir");
        }else{
           
        GestoresContrato gestor1=new GestoresContrato();
        
        
        GestoresContrato gestorCuota2=new GestoresContrato();
        DefaultTableModel mtcc=(DefaultTableModel)tablaCuota.getModel();
        try{
            
        int filas=mtcc.getRowCount();
        int totalCuotas = 0;
        int fil=tablaCuota.getRowCount()-1;
        int tc=Integer.parseInt((String) tablaCuota.getValueAt(fil, 1));
            if(tc==cantidadCuotas){
                
            
            for(int i=0;i<filas;i++){
            
            for(int x=Integer.parseInt((String) tablaCuota.getValueAt(i,0)) ; x <= Integer.parseInt((String) tablaCuota.getValueAt(i,1)); x++){
                
                
            
            Cuota.setContrato(contrato);

            Cuota.setNroCuota(x);
            Cuota.setTotalImpuestos(0);
            Cuota.setValorCuota(Integer.parseInt((String)  tablaCuota.getValueAt(i, 2)));
            
            if(comboComision.getSelectedItem().equals("Monto Fijo")){
               Cuota.setComision(contrato.getHonorarios());
            }else{
               Cuota.setComision(Cuota.getValorCuota()*contrato.getHonorarios());
            }

            if(x<=Integer.parseInt(cuotasGarantia.getText())){       
                float valor=Float.parseFloat(garantia.getText())/Float.parseFloat(cuotasGarantia.getText());
                Cuota.setValorGarantia(valor);
            }else{
                Cuota.setValorGarantia(0);
            }
            Cuota.setTotalaPagar(Cuota.getValorCuota()+Cuota.getTotalImpuestos()+Cuota.getValorGarantia());

            
           gestorCuota2.AltaCuotas(Cuota);
            totalCuotas++;
                
            }
            
        }
            
   //Cargamos el objeto Impuesto
   GestoresImpuestos gestorImp=new GestoresImpuestos();
   String titulares[]={
       
       imp1.getText(),
       imp2.getText(),
       imp3.getText(),
       imp4.getText(),
       imp5.getText(),
       imp6.getText(),
       imp7.getText(),
       imp8.getText(),
       imp9.getText(),
       imp10.getText(),
       imp11.getText(),
       imp12.getText(),
       
   };
   
   for(int i=0;i<titulares.length;i++){
       String texto=titulares[i];
       texto=texto.replaceAll(" ", "");
       if(texto.length()==0){
           
       }else{
           TitularImpuesto titular=new TitularImpuesto();
           DescripcionImpuesto descripcion=new DescripcionImpuesto();
           descripcion.setIdDescripcion((i+1));
           titular.setContrato(contrato);
           titular.setDescipcion(descripcion);
           titular.setTitular(titulares[i]);
           
           gestorImp.GestorAltaTitular(titular);
           
           
       }
   }       
        }else{
               JOptionPane.showMessageDialog(new JDialog(),"La cantidad de precios debe ser igual a la cantidad de Cuotas"); 
            }
            
        try {
            Eventos evento=new Eventos();            
        evento.setUsuario(InicioSesion.usuarioEnSesion);
        evento.setTipo("CONTRATO");
        evento.setDescipcion("Se creo el Contrato "+contrato.getIdContrato());
        evento.setFecha(GestorEventos.getFechaActual());
                gestor1.altaContrato(contrato);
                int m=GestorModificarInmueble.ModificarEstadoOcupado(inm.getId());
                int e=GestorEventos.AltaEvento(evento); 
                this.setCursor(Cursor.WAIT_CURSOR);
                CrearContrato(contrato);
                dispose();
            } catch (IOException ex) {
                Logger.getLogger(NuevoContrato.class.getName()).log(Level.SEVERE, null, ex);
            }
         }catch(ArrayIndexOutOfBoundsException ss){
                    JOptionPane.showMessageDialog(new JDialog(),"Ingrese los precios de las Cuotas");
                    }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void numeroContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroContratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroContratoActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked

        


        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tablaCuotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCuotaMouseClicked

    
    int row=evt.getY()/tablaCuota.getRowHeight();
    int column=tablaCuota.getColumnModel().getColumnIndexAtX(evt.getX());
    
    if(row < tablaCuota.getRowCount() && row >= 0 && column < tablaCuota.getColumnCount() && column >= 0){
        Object value = tablaCuota.getValueAt(row, column);
        if(value instanceof JButton){
            ((JButton)value).doClick();
            JButton boton=(JButton) value;
            DefaultTableModel model=(DefaultTableModel)tablaCuota.getModel();
            model.removeRow(tablaCuota.getSelectedRow());
        }
       
       
        
    }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaCuotaMouseClicked

    private void diaPagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diaPagoKeyTyped

char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_diaPagoKeyTyped

    private void garantiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_garantiaKeyTyped


char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_garantiaKeyTyped

    private void cuotasGarantiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cuotasGarantiaKeyTyped


char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cuotasGarantiaKeyTyped

    private void comisionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comisionKeyTyped


char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_comisionKeyTyped

    private void punitoriosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_punitoriosKeyTyped


char validar=evt.getKeyChar();
        if(Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_punitoriosKeyTyped

    private void imp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imp3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imp3ActionPerformed

    private void imp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imp1ActionPerformed

    private void garantiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_garantiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_garantiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NuevoContrato().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(NuevoContrato.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboComision;
    private javax.swing.JComboBox<String> comboPunitorio;
    private javax.swing.JTextField comision;
    private javax.swing.JTextField cuotasGarantia;
    private javax.swing.JTextField diaPago;
    public static com.toedter.calendar.JDateChooser fechaComienzo;
    public static com.toedter.calendar.JDateChooser fechaVencimiento;
    public static javax.swing.JTextField garante1;
    public static javax.swing.JTextField garante2;
    private javax.swing.JTextField garantia;
    private javax.swing.JTextField imp1;
    private javax.swing.JTextField imp10;
    private javax.swing.JTextField imp11;
    private javax.swing.JTextField imp12;
    private javax.swing.JTextField imp2;
    private javax.swing.JTextField imp3;
    private javax.swing.JTextField imp4;
    private javax.swing.JTextField imp5;
    private javax.swing.JTextField imp6;
    private javax.swing.JTextField imp7;
    private javax.swing.JTextField imp8;
    private javax.swing.JTextField imp9;
    public static javax.swing.JTextField inmueble;
    public static javax.swing.JTextField inquilino;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTextField numeroContrato;
    public static javax.swing.JTextField propietario;
    private javax.swing.JTextField punitorios;
    private javax.swing.JButton seleccionarGara1;
    public static javax.swing.JButton seleccionarGara2;
    private javax.swing.JButton seleccionarInmueble;
    private javax.swing.JButton seleccionarInquilino;
    public static javax.swing.JTable tablaCuota;
    // End of variables declaration//GEN-END:variables

public static int ultimaC;
 
public static Date fechaCc=null;
public static Date fechaVv=null;
public static int cantidadCuotas;
public String titulares[];

public static void CrearContrato(Contrato contrato){
    
    
    Cliente datosPropietario=BusquedaPropietario.busquedaDatos(contrato.getInmueble().getPropietario().getId());
    Cliente datosInquilino=BusquedaPropietario.busquedaDatos(contrato.getInquilino().getId());

    Inmueble datosIn=BusquedaInmueble.busquedaDatosInmueble(contrato.getInmueble().getId());
    String meses[]={"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"};
    try{
            conexion.ConexionReporte con=new conexion.ConexionReporte();
            Map parametro=new HashMap();
            Calendar ahora= Calendar.getInstance();

            int diaActual=ahora.get(Calendar.DATE);
            int mesActual=ahora.get((Calendar.MONTH));
            int añoActual=ahora.get(Calendar.YEAR);
            String inquilino=datosInquilino.getNombre()+" "+datosInquilino.getApellido()+" DNI "+datosInquilino.getDni();
            String domicilioInquilino=datosInquilino.getDireccion();
            String ciudadInq=datosInquilino.getLocalidad()+" de la provincia de "+datosInquilino.getProvincia();
            String propietario=datosPropietario.getNombre()+" "+datosPropietario.getApellido()+" DNI "+datosPropietario.getDni();
            String domicilioProp=datosPropietario.getDireccion();
            String ciudadProp=datosPropietario.getLocalidad()+" de la provincia de "+datosPropietario.getProvincia();
            String nacimientoInq=datosInquilino.getFechaNac();
            String estadoCivil=datosInquilino.getEstadoCivil();
            String apellidoMaterno=datosInquilino.getApellidoMaterno();
            String profesion=datosInquilino.getProfesion();
            String telefono=Integer.toString(datosInquilino.getTel());
            String ciudadInm=datosIn.getLocalidad()+" de la provincia de "+datosIn.getProvincia();
            String domicilioInm=datosIn.getCalle();
            int dniInq=contrato.getInquilino().getDni();
            int mesesContrato=contrato.getTotalCuotas();
            String fechaInicio=contrato.getFechaInicio();
            String fechaFin=contrato.getFechaVencimiento();
            String mes="";
            for(int i=0;i<meses.length;i++){
                mes=meses[mesActual];
            }
            parametro.put("idContrato",contrato.getIdContrato());
            parametro.put("dia",diaActual);
            parametro.put("mes",mes);
            parametro.put("año",añoActual);
            parametro.put("inquilino",inquilino);
            parametro.put("domicilioInquilino",domicilioInquilino);
            parametro.put("ciudadInquilino",ciudadInq);
            parametro.put("propietario",propietario);
            parametro.put("domicilioPropietario",domicilioProp);
            parametro.put("ciudadPropietario",ciudadProp);
            parametro.put("nacimientoInquilino",nacimientoInq);
            parametro.put("estadoCivilInq",estadoCivil);
            parametro.put("apellidoMaternoInq",apellidoMaterno);
            parametro.put("profesionInq",profesion);
            parametro.put("telefonoInq",telefono);
            parametro.put("ciudadInmueble",ciudadInm);
            parametro.put("domicilioInmueble",domicilioInm);
            parametro.put("dniInquilino",dniInq);
            parametro.put("mesesContrato",mesesContrato);
            parametro.put("fechaInicio",fechaInicio);
            parametro.put("fechaFin",fechaFin);
            JasperReport DocContrato=JasperCompileManager.compileReport("C:\\Users\\Nahuel\\Desktop\\SM Inmobiliaria\\src\\Recibos\\contrato.jrxml");           
            JasperPrint jasperPrint=JasperFillManager.fillReport(DocContrato, parametro, con.conexion());
            
            
            contratoDoc.setSize(1000,700);
            contratoDoc.setLocationRelativeTo(null);
            JRViewer jrv=new JRViewer(jasperPrint);
            contratoDoc.getContentPane().add(jrv);
            contratoDoc.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(PrincipalAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
}
}
